import { outdent } from 'outdent';

import type { TemplateFile } from '../../types';

const eslintIgnoreFile: TemplateFile = {
  name: 'eslint.config.js',
  contents: outdent`
      // AUTOGENERATED FILE: I believe you know what you are doing.
      module.exports = [
        {
          ignores: ['dist']
        }
      ]
    `,
};

export { eslintIgnoreFile };
